### ISSUE TITLE
Siebel IP 20 - "Session Warning Message" every time

### ISSUE THREAD

**Issue by bassista** [Blazemeter/CorrelationRecorder#16]
I am trying to register a simple interaction towards siebel version IP 20, in which I log in and search for a customer and request his details. Everything seems to work but when I replay the registration to the customer detail request I always get an error page as a response that says: "Session Warning Message", which warns me of the existence of another session open for the same user. I verified that the request that goes in error is identical to the previous one, which instead receives a correct answer, has the same parameters (apart from the frame parameter) and the same JsessionId present in the cookie. Is the plugin compatible with Siebel IP version 20? I haven't changed or added any correlation rules this scenario shouldn't work out of the box? Thanks so much for your effort.

**Comment by RicardoPoleo** [comment]
Hello @bassista,

Thanks for taking the time to give a detailed explanation and report your situation to us. This, we highly appreciate it.

The rules provided by the Siebel CRM Template are the ones we thought were the most used but, those ain't bulletproof and we are still improving some functionalities. At any rate, until now, we haven't faced that issue before.

I got some questions that I need to know in order to see if it's an issue related to the plugin or its configuration related.

1. Did you used Incognito Mode? (To avoid sessions issues for the recorder)
2. Are you using the Correlation Recorder Template (loaded from File -> Templates - > bzm - Correlation Recorder)? Or you are directly adding the Correlation Recorder into a Test Plan? 
2. Which version of the Correlation Recorder are you using?
3. Which version of JMeter does this issue happens?
4. It is possible that you could share the JTL of the recording and the playback? (you can remove the sensitive info if you need to). In this case, please configure it using these options:

![JTLRecordingConfiguration](https://user-images.githubusercontent.com/7467545/102518702-5e725c80-4070-11eb-94cf-246f40dfe627.png)

At any rate, hope to hear from you soon and, as always,

Happy Hacking!

**Comment by RicardoPoleo** [comment]
Hello @bassista,

How are you doing? It has been a while since the last time we spoke. Did you have any news regarding the files and questions we asked you?

I hope you are doing ok.

**Comment by RicardoPoleo** [comment]
Hello @bassista,

Its been a while since the last time we spoke. Due to the fact that you have not answered our inquiries, I'll assume everything worked in the end.

I'll be closing this issue but, please, if you have anything else to provide or ask, don't hesitate to reopen it.

See you around!
