### ISSUE TITLE
Error occured while copying node

### ISSUE THREAD

**Issue by QAInsights** [Blazemeter/CorrelationRecorder#2]
After recording the business flow using the Correlation Recorder plugin, when we cut the any recorded element, JMeter is throwing below error.

Version: JMeter 5.3

![image](https://user-images.githubusercontent.com/2826376/83708696-686cca80-a60c-11ea-913e-79d48f9d8f5d.png)

**Comment by Baraujo25** [comment]
Hello,

Thanks for reaching out! I apologize for the trouble you are having while using Correlation Recorder.

We have already added your issue to our backlog in order to be included in our next release. 
In the meantime, I would suggest deleting the one you want to cut and then create a new one. 

Remember that if you have any rules added in the Correlation Recorder element, it is possible by clicking the [save](https://github.com/Blazemeter/CorrelationRecorder#saving-and-loading-rules) button to create a template, then you have access to that template whenever you want from all Correlation Recorder elements.

Best regards

**Comment by QAInsights** [comment]
Thanks @Baraujo25 for the update.

**Comment by RicardoPoleo** [comment]
Hello, @QAInsights

Hope you are doing amazing! 

Recently we released a new version of the plugin that handles the issue of copy/cutting/pasting elements within the Test Plan when the Correlation Recorder is loaded on it.

Could you give it a try and see if this fixed the issue you were having?

Hope to hear from you soon,

**Comment by RicardoPoleo** [comment]
Hello @QAInsights ,

Just like other issues that were fixed on our last release, I'll be closing this issue due to a lack of activity.

Feel free to reopen it if you see the problem persist,

Have a nice day
