### ISSUE TITLE
Blazemeter correlation recorder for mendix platform

### ISSUE THREAD

**Issue by prithiviraj04** [Blazemeter/CorrelationRecorder#20]
I added bzm-correlation recorder plugin in Jmeter(version 5.2.1). As per the documentaion, I gave correlation rules and captured the scenario.

Result I got:
As expected, regular expression extractor is automatically added to the request which matches the regular expression given in correlation rule.
But the dynamic value in the subsequent requests i can't replace properly due to mendix application will have the requests like below:

{"action":"executemicroflow","params":{"name":"JoinForm.IVK_JoinForm_Next_FinancialConfirmation","params":{"Agent":{"guid":"49821070877903922"}},"validationGuids":["103582791429984673","49821070877903922","74027918875004238","4503599627474506","55732045388813898","2533274790499914"]},"changes":{"23925373020765797":{"Duration":{"value":"0.31065111"}},"97671816918664942":{"Feedback_FindSponsor":{"value":""}}},"objects":[],"profiledata":{"1614601854093-117":1069}}

And also its creating multiple extractor for single value as I attached the screenshot here for your reference.

Kindly guide me to solve this issue. Thanks in advance.
![image](https://user-images.githubusercontent.com/81344362/112419352-484ff880-8d51-11eb-9ac7-0193f93aa505.png)

**Comment by RicardoPoleo** [comment]
Hello @prithiviraj04,

Thanks for taking the time to request assistance regarding this matter.

Before trying to see what is your particular issue. Please share with us:
* The TestPlan (containing the Rules used to do the Correlation)
* The Recording JTL 

Have in mind that, for us to test your particular case (and see if it an issue from our side or something regarding the configuration of the rules), the JTL should be using these options:

![](https://user-images.githubusercontent.com/7467545/102518702-5e725c80-4070-11eb-94cf-246f40dfe627.png).

That would speed up the troubleshooting process. 

---

That being said and without the mentioned files to guide us about your problem, I'm under the impression that one of the following scenarios could be worth reviewing: 

# The Extracted Value being overwritten

The value you want to extract and, subsequently replace, is being overwritten by one of the multiple Regex Extractor that was added in the other recorded samples.

## Possible solution

You could check the "MultiValued" checkbox in the Correlation Extraction Rule(s) that generates those Regex Extractors. This will keep each of the extracted values in a different variable.

Have in mind that, if you have "multiple Regex Extractors" in your recorded Test Plan, this means that the Regular expression you used "matched in each one of them", therefore, it added extraction post-processor to store that matched value. This could also mean that you should use, if possible, a more specific Regular Expression, to avoid matching many times during the recording.

# The Replacement Regex do not match the Request format (XML, JSON, among others)

One common mistake is using the same Regular Expression used for the Extraction to do the replacement. If the Regex does not match, then it will not be able to apply the Replacement.

## Possible solution

Test the Regular Expression used in your Correlation Replacement, and see it matches. Tools like [Regex101](https://regex101.com/) or [RegExr](https://regexr.com/) are quite useful for that.

Checking the JSON you sent, and assuming you want to replace the *guid*, I would say that the Regex needed should be: `{"guid":"([0-9]+)"}`.

# The Regex matches but still does not apply the Replacement

This is also a pretty common case: If the Regex matches in the Request but still do not apply the replacement, it is probably because the value stored in the variable and the matched in the request, are different, hence, the Replacement will no be applied. 

Take for instance the case of *guid* in the JSON you shared with us: if the value stored is different from `49821070877903922`, the Correlation Recorder do not know if this is the one that needs to be replaced (unless, of course, you checked the "Ignore Value" checkbox in the Regex CR configuration, which is useful on situations where you "generate" the value, instead of extracting it, and I think that's not the case here).

## How to know if this applies to you

Checking the value that is assigned to the variable by the moment the request is made is quite simple to be done:

1. Enable the Debug Post Processor that comes with the Correlation Recorder Template 
2. Run the replay of the recording 
3. Go to the View Request Tree inside the Recording Controller 
4. Click on the Request where the Replacement should be done (it should contain a child, that's the one we need to check)
5. Click on Response Data --> Response Body

Here you will be presented with all the variables and their values by the moment the request was made. If the variable of the Rule where your Correlation Replacement is configured, has another value different from the one that is used in the request, then we need to check all possible reasons, as mentioned in the other sections.

---
# Final Note

Please review those comments and, if you still have issues dealing with this problem, do not hesitate to share those files and we will take a deeper look into them. The Correlation Recorder plugin is fully prepared to do replacements in JSONs so, for that particular situation, you do not need to worry.

Have a nice day and, as always,

Happy Hacking!

**Comment by prithiviraj04** [comment]
Can we have call so that I can explain you clearly.

**Comment by prithiviraj04** [comment]
I need help with this. I want to replace hash value so I tried with `"hash":"(.*?)"` and `"hash":"(.+?)"` both are not working and same for queryId.

```JSON
{
	"action": "query_by_path",
	"params": {
		"id": "${ConfigurationSearchHelperUser#9}",
		"queryId": "+ynish40Y0W6u8sPENCHrQ"
	},
	"changes": {
		"${JoinForm.CommercialDisplay#31}": {
			"Show": {
				"value": "All"
			},
			"JoinForm.CommercialDisplay_SearchHelper": {
				"value": "${ConfigurationSearchHelperUser#9}"
			}
		}
	},
	"objects": [{
		"attributes": {
			"Commercial": {
				"value": false
			},
			"JoinForm.CommercialDisplay_SearchHelper": {
				"value": null
			},
			"Show": {
				"value": null
			},
			"JoinForm.CommercialDisplay_User": {
				"value": null
			}
		},
		"guid": "${JoinForm.CommercialDisplay#31}",
		"hash": "OT+vxuVo1ratJVCKORQdRnF5m/P9/TwDD8B4x9AZ+nY",
		"objectType": "JoinForm.CommercialDisplay"
	}],
	"profiledata": {
		"1617000944134-41": 1087
	}
}
```

**Comment by QAInsights** [comment]
@prithiviraj04 please use this reg ex 
```
hash\":\"(.+?)\"
queryId\":\"(.+?)\"
```

**Comment by prithiviraj04** [comment]
@QAInsights Thanks for your reply

For `queryId` I tried with regex `queryId":"(.+?)"` was working but, for the hash, I tried multiple combinations even above mentioned regex `hash\":\"(.+?)\"` also not working which is not replacing may hash value.

**Comment by RicardoPoleo** [comment]
I agree with @QAInsights on his proposal, the regex for the Regex Correlation Replacement works fine for me. Check the link for an example: https://regexr.com/5q2o7, and also you can see a preview in the following picture:

![Screen Shot 2021-04-05 at 10 23 48](https://user-images.githubusercontent.com/7467545/113584559-0b112380-95f9-11eb-819b-7f9f1e6d6e1d.png)

The above regex works **for the Correlation Replacement**. I assume you might be having *troubles* with the value that is stored in the reference variable and that's the main reason the replacement doesn't work.

---
Let's try an overkill approach and run down from that point. Try adding this rule to your configurations:

| Reference Variable | 
| - | 
| HashIdTest |

*Corr. Extractor Config*

| Type | Regex | Match Nr | Group Nr | Target | MultiValue |
| - | - | - | - | - | - |
| Regex | Your Regex | 1 | 1 | Body | Checked |

*Corr. Replacement Config*
| Type | Regex | Replacement String | Ignore Value | 
| - | - | - | - |
| Regex | `\"hash\":\"(.+?)\"` | (Leave empty)  | Unchecked | 

**I highly encourage you to add** a Debug Post Processor for the recorded steps and check the value you have on the Reference Variable for the Sampler when the replay is done. This will allow us to discard either is a problem with the Replacement or with the Extracted value.

Please try it and let us see how it works.

---

If you keep having problems or think the data is too sensitive to share on GitHub, send me a mail to ricardo.poleo@broadcom.com and we will check it together.

As always,

Happy Hacking & Good Luck!

**Comment by prithiviraj04** [comment]
@QAInsights & @RicardoPoleo Thanks for your reply.

Still its not replacing, as you mentioned I tried in https://regexr.com its working there but not in my script.

**Comment by QAInsights** [comment]
@prithiviraj04 I believe there is a space between the key (hash) and its value. You can handle the white space using the below reg ex. You can check out my regular expression tutorial videos in [here](https://www.youtube.com/watch?v=9TaHParYnrc&list=PLJ9A48W0kpRLorIGHOM7g2OUsO2de3ERm).
```
\s*\"hash\":\s*\"(.+?)\"
```
or
```
\"hash\":\s*\"(.+?)\"
```

**Comment by prithiviraj04** [comment]
@QAInsights

**Comment by prithiviraj04** [comment]
@QAInsights 

As discussed earlier "=" sign only making issue for me because while recording through correlation recorder its skipping the "=" sign in my script so my hash value will also have "=" sign so extractor variable having my hash value with "="sign but in my script it was not having "=" sign for my hash value so that its not replacing before. Now even "hash":"(.+?)" this extractor also working fine.

But please fix "=" sign missing while recording through correlation recorder.

**Comment by prithiviraj04** [comment]
@RicardoPoleo 

When should I expect that next release which fixed "=" sign?

**Comment by RicardoPoleo** [comment]
Hello @prithiviraj04,

The fix for this issue was released on version [1.1.2](https://github.com/Blazemeter/CorrelationRecorder/releases/tag/v1.1.2) of the plugin, you can check it out. 

With this, the correlation should be working.

I'll be closing this issue but, if you have any problem, don't hesitate to reopen it.

Happy hacking,

**Comment by prithiviraj04** [comment]
Now All working properly. Thanks for new release.

I need 1 clarification. I have correlation extractor but correlation replacement should be 2 different types. Example

"value":"22a96417-a272-11eb-bc94-010925e8f132"
Uuid=22a96417-a272-11eb-bc94-010925e8f132&RedirectUrl

how can I handle this?

**Comment by sebastianlorenzo88** [comment]
You could create a rule with the extractor and one of the replacements and then another rule with the same var name and the other replacement but with none extractor

For example 

![image](https://user-images.githubusercontent.com/33757553/115762286-afc18e00-a379-11eb-901e-75f970578f7d.png)

**Comment by prithiviraj04** [comment]
Oh thankyou @sebastianlorenzo88

**Comment by prithiviraj04** [comment]
Hi

var1=78563963374434
guid":"${var1}","hash":"(.+?)","objectType":"Transaction.Transaction"

In normal regex I can use the above condition if I have the var1 then I can use it in my upcoming request. Likewise Is that possible to use the above condition in correlation extractor rules in correlation recorder?

**Comment by RicardoPoleo** [comment]
Hello @prithiviraj04,

Thanks for taking the time to post in our repo. I highly encourage you to open a new thread asking this kind of questions, it is more likely to get a faster answer that way.

Regarding your question, I think you want to extract the **hash** only if the **guid** is already extracted and it also matches. Something like:

1. Rule 1: Extract `guid`, store it on var1
2. Rule 2: Extract `hash`, store in on `var2`. Only applies if the value on `var1` was previously extracted and, when the value is resolved, the whole RegEx matches.

If that's the case, then, no, the Correlation Recorder does not support, by default, that functionality.

The [Custom Extensions](https://github.com/Blazemeter/CorrelationRecorder#making-your-own-extensions), on the other hand, could serve you to implement this custom logic.
 
Hope this helps,

Keep up with the good work,

**Comment by Jetawi** [comment]
Hello,

How Can I correlate the queryId value since it's required in the request while it's not displayed in any previous responses ?
