### ISSUE TITLE
Some HTTP requests are missing when recorded with correlation recorder plugin

### ISSUE THREAD

**Issue by RagaveniSundaresan** [Blazemeter/CorrelationRecorder#27]
When recording the scenario using the bzm correlation plugin, some of the main http requests are not captured. Because of this validation could not be done. We verified the application without using the plugin, all http requests are capturing. Also few requests are capturing out of order with plugin. For example, http-1,http-2,http-3, http-4,http-5 is the expected order. But recorded order is http-1,http-5,http-3,http-4,http-2. 
What happens here is http-5 request's values depends on http2's response. Due to the unexpected order, auto correlation behaviour of the plugin is affecting.

**Comment by RicardoPoleo** [comment]
Hello @RagaveniSundaresan,

Would you let us know the following:
1. The JMeter Version
2. The Plugin Version
3. Any particular protocol you are recording (Siebel, for instance)

We are aware that, after JMeter 5.3, the plugin copies some behaviors from JMeter related to requests that _takes longer than expected_ to provide a response, thus, they might be recorded on a different order, that's why I'm kindly asking about the version.

Please provide this information, and we can diagnose your issue more accurately.

 Kind Regards,

Ricardo

**Comment by RagaveniSundaresan** [comment]
Hi Ricardo,

 

Jmeter version – 5.4.3

Plugin version – 1.2

Not recording with any particular protocol.

 

Regards,

Ragaveni

**Comment by RagaveniSundaresan** [comment]
Hi Ricardo,

 

Any updates regarding the issue which I raised?

 

Regards,

Ragaveni

 

From: Ragaveni ***@***.*** 
Sent: 08 July 2022 16:01
To: 'Blazemeter/CorrelationRecorder'; 'Blazemeter/CorrelationRecorder'
Cc: 'Mention'
Subject: RE: [Blazemeter/CorrelationRecorder] Some HTTP requests are missing when recorded with correlation recorder plugin (Issue #27)

 

Hi Ricardo,

 

Jmeter version – 5.4.3

Plugin version – 1.2

Not recording with any particular protocol.

 

Regards,

Ragaveni

**Comment by RicardoPoleo** [comment]
Hello @RagaveniSundaresan,

Sorry for our late response. I would recommend you, as a workaround, to use the plugin with JMeter 5.2.1 or 5.3, since we have experienced that, in later versions, this might occur.

I added this issue to our backlog, and it is likely that we will tackle it next month.

Please let me know how goes your testing with those versions and, when we tackle this, we will let you know as well.

Best regards,

**Comment by RagaveniSundaresan** [comment]
Hi Ricardo,

 

Sure, I will try with JMeter 5.2.1 or 5.3 versions as you suggested and we will let you know in case of any issue.

 

Regards,

Ragaveni

**Comment by RicardoPoleo** [comment]
Hi @RagaveniSundaresan,

did the work around worked for you?

Thanks,

**Comment by RicardoPoleo** [comment]
I'll close this issue and, if you had another input, please reopen it.

Thanks
