### ISSUE TITLE
Recording with JMeter 5.5 version is broke

### ISSUE THREAD

**Issue by mjohnson767** [Blazemeter/CorrelationRecorder#28]
Version 5.4.3 of JMeter has been working great with the Correlation recorder version 1.2. 
Moving to JMeter 5.5 broke all the templates, which is fine but recording the traffic while using the correlation recorder is broke. The script will sometimes start to show up in the Thread Group and then stops part way through a recording or doesn't build out at all. 

The View Results Tree of the recorder displays all the necessary traffic to make the script. 

Attempting to record traffic with or without recording rules results in same behavior. 
Same with and without any requests filtering.

I'm on a Windows 10 developers laptop. 

I've attempted to use the version 1.0 of the Correlation recorder with version 5.5 of JMeter and that doesn't work either. JMeters built in recorder works every time with no issues. 

Our Entire team has moved to using the latest version of JMeter; are there any plans to update the Correlation Recorder?
![Ping_ViewState_Rules-1-snapshot](https://user-images.githubusercontent.com/51394643/182257955-4de745d5-a853-4948-898c-4512594132c9.png)
![ViewResultsTree](https://user-images.githubusercontent.com/51394643/182258124-1976b16a-4c07-4f99-9ea0-1e3777e57568.png)

**Comment by RicardoPoleo** [comment]
Hello @mjohnson767,

Thanks for both taking the time to report this issue and also document it so well, every feedback makes this plugin much better!

We were aware of an issue regarding the traffic not being recorded (sometimes) in JMeter versions superior to the 5.3 however, not that it broke the templates. That's a shame, and we are sorry about it.

I'll add it to our backlog to tackle it as soon as our team's priorities allows it (we will be making a release of other BlazeMeter plugin this week and tackle this in the following sprints).

In the meanwhile, we usually recommend our users to use JMeter 5.3 or JMeter 5.2.1 however, _you were working with JMeter 5.4.3 and everything ran perfectly_? If that's the case, I would ask you to continue doing so until we make a release fixing this issue.

Please let me know if there is something else I can help you with, and I'll keep you posted upon the fix is done and released.

Thanks, @mjohnson767 and happy hacking!

**Comment by mjohnson767** [comment]
I've switched back to JM version 5.4.3 for building tests for now. Further testing with the plugin simply doesn't work with recording in version 5.5. It's been a really great plugin to use and I've even gave demo's using it. I'm a little surprised Apache doesn't implement something of the same. Can you let me know of your plans? Are you going to implement fixes for JM 5.5 and so on?

**Comment by RicardoPoleo** [comment]
Hello @mjohnson767,

We are planing to both provide support for the new versions, and we have some features under the sleeve as we can't reveal just yet 🕵️  that will greatly enhance the plugin usability 🤯.

That being said, you can always reach me out for both feedback or inquiries to ricardo.poleo@blazemeter.com. We are thrilled that you had a success using it in your demo.

**Comment by 3dgiordano** [comment]
Hi @mjohnson767 

We made a release with several compatibility improvements.
Could you carry out tests with this version and tell us if it solves the problems reported?

https://github.com/Blazemeter/CorrelationRecorder/releases/tag/v1.2.3

**Comment by RicardoPoleo** [comment]
Closed due inactivity
