### ISSUE TITLE
Zoom In/Out UI

### ISSUE THREAD

**Issue by QAInsights** [Blazemeter/CorrelationRecorder#5]
After adding rules and if the user zooming in/out, the first row is getting invisible partially. Please check the below screenshot.

![image](https://user-images.githubusercontent.com/2826376/83779804-ecaa6680-a67b-11ea-989d-7aae502166ce.png)

**Comment by RicardoPoleo** [comment]
Hello, @QAInsights  

Since we changed the UI for the Correlation Rules, this issue looks fixed on our end but, this might not be your case on your machine. Please check out the [last release](https://github.com/Blazemeter/CorrelationRecorder/releases), and let us know if you have any issues. 

Just like the other ones, I'm closing this issue but, don't hesitate to open it again if you experience this kind of behavior with the new implementation.

Happy hacking & enjoy!
