### ISSUE TITLE
HTTP 2 recording with correlation recorder

### ISSUE THREAD

**Issue by fbaptista** [Blazemeter/CorrelationRecorder#56]
**Describe the feature**

Currently, near 50% of top 1.000.000 websites uses HTTP/2 protocol and 70% of top 1000 websites also relies on this protocol ([ref](https://w3techs.com/technologies/comparison/ce-http2,ce-httpsdefault)). 
It would be nice if this Correlation Recorder could record http2 scripts, since it will unlock its usage on webapps running on modern web servers.

**Comment by 3dgiordano** [comment]
Hi @fbaptista 

Currently Correlation Recorder supports recording what JMeter supports recording and running.

Currently, since there are no requests in this regard, we have not invested in going beyond what is supported by JMeter.

If there is an initiative by the HTTP2 plugin that takes advantage of JMeter's extensibility functionality at the protocol level and allows its proxy to write in HTTP2 format

If you use the HTTP2 plugin
https://github.com/Blazemeter/jmeter-http2-plugin/

And you enable the experimental functionality by adding the following property in jmeter.properties

HTTP2Sampler.proxy_enabled=true

With that you will have HTTP2 support in JMeter and with it also in Correlation Recorder.

**Comment by fbaptista** [comment]
Thank you so much @3dgiordano we will try this!
