### ISSUE TITLE
could not find release 2.6 in maven central repository

### ISSUE THREAD

**Issue by gulecroc** [Blazemeter/CorrelationRecorder#78]
Hello,

The release 2.6 does not exist in the maven central repository : https://mvnrepository.com/artifact/com.blazemeter/jmeter-bzm-correlation-recorder

![image](https://github.com/user-attachments/assets/f38ef983-0e44-438d-9380-71617482eedb)

Could you please push it ?

Thank you
Guillaume

**Comment by Baraujo25** [comment]
Hello @gulecroc,

Thank you for reaching out. Yes, you are right! As you could see on the Github Actions the [release process](https://github.com/Blazemeter/CorrelationRecorder/actions/runs/10516236265) failed on that step.

You can expect to be fixed by the end of the week.

Thank you so much for using the plugin!

**Comment by gulecroc** [comment]
Hello @Baraujo25 , do you have any update ? Thank you

**Comment by 3dgiordano** [comment]
Hi @gulecroc 
Sorry for not having made the announcement, the release issue was fixed.
Version 2.6 is now available for use from maven.

https://mvnrepository.com/artifact/com.blazemeter/jmeter-bzm-correlation-recorder

**Comment by gulecroc** [comment]
Thank you all !
